name: Question about RAPID
description: If you would like to ask a question about RAPID.
title: "[question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to ask us about RAPID!
  - type: textarea
    attributes:
      label: What would you like to ask?
      description: >
        All questions are good questions!
      placeholder: Can you please tell us...?
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Let us ensure open source development is sustainable!
      description: >
        We care about open source, and we would like for our interactions to be
        a productive collaboration!
      options:
        - label: >
            I have read the last paragraph of Section 6.3 in
            [David et al., 2016](https://doi.org/10.1002/2015EA000142).
          required: true
        - label: >
            I have looked at previous GitHub issues and this question has not
            yet been addressed.
          required: true
