#*******************************************************************************
#rapid_github_actions.yml
#*******************************************************************************

#Purpose:
#GitHub Actions is a continuous integration and continuous delivery (CI/CD)
#platform that allows to automate the build, test, and deployment pipeline. The
#The purpose of this file is to give instructions to GitHub on how to do the
#work.
#Author:
#Cedric H. David, 2022-2022.


#*******************************************************************************
#Name and specification of triggers
#*******************************************************************************
name: RAPID GitHub Actions
on:
   push:
   pull_request:


#*******************************************************************************
#Jobs
#*******************************************************************************
jobs:

   #----------------------------------------------------------------------------
   #Ubuntu
   #----------------------------------------------------------------------------
   ubuntu:
      runs-on: ubuntu-18.04
      strategy:
         matrix:
            include:
               - dwnl: "./tst_pub_dwnl_David_etal_2011_JHM.sh"
                 repr: "./tst_pub_repr_David_etal_2011_JHM.sh 1 15"
               - dwnl: "./tst_pub_dwnl_David_etal_2011_JHM.sh"
                 repr: "./tst_pub_repr_David_etal_2011_JHM.sh 16 23"
               - dwnl: "./tst_pub_dwnl_Emery_etal_2020_JHM2.sh"
                 repr: "./tst_pub_repr_Emery_etal_2020_JHM2.sh"
      steps:

      #- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      #Checkout RAPID code
      #- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         - name: Checkout RAPID code
           uses: actions/checkout@v2

      #- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      #Display GitHub Action-related information
      #- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         - name: Display GitHub Action-related information
           run: |
              echo "This job was triggered by a ${{ github.event_name }} event."
              echo "This job is running on a ${{ runner.os }} server at GitHub!"
              echo "The name of the repository is ${{ github.repository }}."
              echo "The name of the branch is ${{ github.ref }}."
              echo "The current working directory is $PWD"
              echo "The GitHub workspace is ${{ github.workspace }}"
              echo "The shell used is $SHELL"

      #- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      #Install OS requirements
      #- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         - name: Install OS requirements
           run: sudo apt-get update
         - run: sudo apt-get install -y --no-install-recommends gcc

      #- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      #Run tests
      #- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         - name: Run tests
           env:
              TST_PUB_DWNL: ${{matrix.dwnl}}
              TST_PUB_REPR: ${{matrix.repr}}
           run: |
              echo $TST_PUB_DWNL
              echo $TST_PUB_REPR


#*******************************************************************************
#End
#*******************************************************************************
